//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 04:35:05 PM CEST 
//


package com.example.model.amandman;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/XML/tim8/amandman}promena" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pravni_osnov" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="akt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="odbornik" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="PREDLOZEN"/>
 *             &lt;enumeration value="USVOJEN"/>
 *             &lt;enumeration value="ODBIJEN"/>
 *             &lt;enumeration value="POVUCEN"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="za" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="protiv" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="uzdrzano" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="raw_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="procenat" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="akt_raw_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "promena"
})
@XmlRootElement(name = "amandman")
public class Amandman {

    @XmlElement(required = true)
    protected List<Promena> promena;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "naziv", required = true)
    protected String naziv;
    @XmlAttribute(name = "pravni_osnov", required = true)
    protected String pravniOsnov;
    @XmlAttribute(name = "akt", required = true)
    protected String akt;
    @XmlAttribute(name = "odbornik", required = true)
    protected String odbornik;
    @XmlAttribute(name = "status", required = true)
    protected String status;
    @XmlAttribute(name = "za")
    protected Integer za;
    @XmlAttribute(name = "protiv")
    protected Integer protiv;
    @XmlAttribute(name = "uzdrzano")
    protected Integer uzdrzano;
    @XmlAttribute(name = "raw_id", required = true)
    protected String rawId;
    @XmlAttribute(name = "procenat")
    protected Double procenat;
    @XmlAttribute(name = "akt_raw_id")
    protected String aktRawId;

    /**
     * Gets the value of the promena property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promena property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromena().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Promena }
     * 
     * 
     */
    public List<Promena> getPromena() {
        if (promena == null) {
            promena = new ArrayList<Promena>();
        }
        return this.promena;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravniOsnov() {
        return pravniOsnov;
    }

    /**
     * Sets the value of the pravniOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravniOsnov(String value) {
        this.pravniOsnov = value;
    }

    /**
     * Gets the value of the akt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAkt() {
        return akt;
    }

    /**
     * Sets the value of the akt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAkt(String value) {
        this.akt = value;
    }

    /**
     * Gets the value of the odbornik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdbornik() {
        return odbornik;
    }

    /**
     * Sets the value of the odbornik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdbornik(String value) {
        this.odbornik = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the za property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getZa() {
        return za;
    }

    /**
     * Sets the value of the za property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setZa(Integer value) {
        this.za = value;
    }

    /**
     * Gets the value of the protiv property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProtiv() {
        return protiv;
    }

    /**
     * Sets the value of the protiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProtiv(Integer value) {
        this.protiv = value;
    }

    /**
     * Gets the value of the uzdrzano property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUzdrzano() {
        return uzdrzano;
    }

    /**
     * Sets the value of the uzdrzano property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUzdrzano(Integer value) {
        this.uzdrzano = value;
    }

    /**
     * Gets the value of the rawId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRawId() {
        return rawId;
    }

    /**
     * Sets the value of the rawId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRawId(String value) {
        this.rawId = value;
    }

    /**
     * Gets the value of the procenat property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getProcenat() {
        return procenat;
    }

    /**
     * Sets the value of the procenat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProcenat(Double value) {
        this.procenat = value;
    }

    /**
     * Gets the value of the aktRawId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAktRawId() {
        return aktRawId;
    }

    /**
     * Sets the value of the aktRawId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAktRawId(String value) {
        this.aktRawId = value;
    }

}
