//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 04:35:05 PM CEST 
//


package com.example.model.amandman;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.example.model.akt.Alineja;
import com.example.model.akt.Clan;
import com.example.model.akt.Podtacka;
import com.example.model.akt.Stav;
import com.example.model.akt.Tacka;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/XML/tim8/akt}clan" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/XML/tim8/akt}stav" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/XML/tim8/akt}tacka" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/XML/tim8/akt}podtacka" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/XML/tim8/akt}alineja" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="odredba" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tip" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="brisanje"/>
 *             &lt;enumeration value="izmena"/>
 *             &lt;enumeration value="dopuna"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="sluzbeno_glasilo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="obrazlozenje" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "promena")
public class Promena {

    @XmlElementRefs({
        @XmlElementRef(name = "stav", namespace = "http://www.ftn.uns.ac.rs/XML/tim8/akt", type = Stav.class, required = false),
        @XmlElementRef(name = "alineja", namespace = "http://www.ftn.uns.ac.rs/XML/tim8/akt", type = Alineja.class, required = false),
        @XmlElementRef(name = "tacka", namespace = "http://www.ftn.uns.ac.rs/XML/tim8/akt", type = Tacka.class, required = false),
        @XmlElementRef(name = "clan", namespace = "http://www.ftn.uns.ac.rs/XML/tim8/akt", type = Clan.class, required = false),
        @XmlElementRef(name = "podtacka", namespace = "http://www.ftn.uns.ac.rs/XML/tim8/akt", type = Podtacka.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "odredba", required = true)
    protected String odredba;
    @XmlAttribute(name = "tip", required = true)
    protected String tip;
    @XmlAttribute(name = "sluzbeno_glasilo", required = true)
    protected String sluzbenoGlasilo;
    @XmlAttribute(name = "obrazlozenje", required = true)
    protected String obrazlozenje;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stav }
     * {@link Clan }
     * {@link Alineja }
     * {@link Tacka }
     * {@link String }
     * {@link Podtacka }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the odredba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdredba() {
        return odredba;
    }

    /**
     * Sets the value of the odredba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdredba(String value) {
        this.odredba = value;
    }

    /**
     * Gets the value of the tip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTip(String value) {
        this.tip = value;
    }

    /**
     * Gets the value of the sluzbenoGlasilo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSluzbenoGlasilo() {
        return sluzbenoGlasilo;
    }

    /**
     * Sets the value of the sluzbenoGlasilo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSluzbenoGlasilo(String value) {
        this.sluzbenoGlasilo = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObrazlozenje(String value) {
        this.obrazlozenje = value;
    }

}
