//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 04:35:05 PM CEST 
//


package com.example.model.akt;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml.tim8.akt package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml.tim8.akt
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Akt.Deo }
     * 
     */
    public Akt.Deo createAktDeo() {
        return new Akt.Deo();
    }

    /**
     * Create an instance of {@link Akt.Deo.Glava }
     * 
     */
    public Akt.Deo.Glava createAktDeoGlava() {
        return new Akt.Deo.Glava();
    }

    /**
     * Create an instance of {@link Akt.Deo.Glava.Odeljak }
     * 
     */
    public Akt.Deo.Glava.Odeljak createAktDeoGlavaOdeljak() {
        return new Akt.Deo.Glava.Odeljak();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Stav }
     * 
     */
    public Stav createStav() {
        return new Stav();
    }

    /**
     * Create an instance of {@link Tacka }
     * 
     */
    public Tacka createTacka() {
        return new Tacka();
    }

    /**
     * Create an instance of {@link Podtacka }
     * 
     */
    public Podtacka createPodtacka() {
        return new Podtacka();
    }

    /**
     * Create an instance of {@link Alineja }
     * 
     */
    public Alineja createAlineja() {
        return new Alineja();
    }

    /**
     * Create an instance of {@link Akt.Deo.Glava.Odeljak.Pododeljak }
     * 
     */
    public Akt.Deo.Glava.Odeljak.Pododeljak createAktDeoGlavaOdeljakPododeljak() {
        return new Akt.Deo.Glava.Odeljak.Pododeljak();
    }

}
